name: default
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: dev
    - run: flutter config --enable-windows-desktop
    - run: flutter pub get
    - run: cd example && flutter build windows
